apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-index-one
data:
  index.html: |
    <html>
      <body>
        <h1>This is Deployment One</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-one
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: custom-index
          mountPath: /usr/share/nginx/html
          subPath: index.html
      volumes:
      - name: custom-index
        configMap:
          name: custom-index-one
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-index-two
data:
  index.html: |
    <html>
      <body>
        <h1>This is Deployment Two</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: custom-index
          mountPath: /usr/share/nginx/html
          subPath: index.html
      volumes:
      - name: custom-index
        configMap:
          name: custom-index-two
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort
